# Generated by Django 5.2.17 on 2026-10-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттамасы')),
                ('status', models.CharField(choices=[('todo', 'Жоспарланған'), ('in_progress', 'Орындалып жатыр'), ('done', 'Аяқталған')], default='todo', max_length=20, verbose_name='Күйі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['todo', 'in_progress', 'done'])), name='task_status_valid')],
            },
        ),
    ]
